#!/usr/bin/env bash
set -euo pipefail
# mosquitto.sh — manage a local MQTT broker for OTA testing
# Usage: scripts/mosquitto.sh <action>
#
# Actions:
#   up       Start the broker (idempotent)
#   down     Stop the broker (idempotent)
#   status   Show running status
#   restart  Stop then start
#
# Environment:
#   LOCAL_MQTT_PORT (default 1883) Broker port

action="${1:-}"
port="${LOCAL_MQTT_PORT:-1883}"
config_dir="target/mosquitto"
config_file="$config_dir/mosquitto.conf"
log_file="$config_dir/mosquitto.log"
pid_file="$config_dir/mosquitto.pid"

usage() {
    echo "Usage: $0 <up|down|status|restart>" >&2
    exit 2
}

[ -n "$action" ] || usage

# Find mosquitto binary
find_mosquitto() {
    if command -v mosquitto >/dev/null 2>&1; then
        command -v mosquitto
    elif [ "$(uname)" = "Darwin" ]; then
        # Try Homebrew location on macOS
        local brew_prefix
        if brew_prefix=$(brew --prefix 2>/dev/null); then
            echo "$brew_prefix/sbin/mosquitto"
        else
            return 1
        fi
    else
        return 1
    fi
}

mosquitto_bin=$(find_mosquitto || echo "")
if [ -z "$mosquitto_bin" ] || [ ! -x "$mosquitto_bin" ]; then
    echo "Error: mosquitto binary not found. Install with: brew install mosquitto" >&2
    exit 1
fi

# Ensure config directory exists
mkdir -p "$config_dir"

# Check if broker is running (pid file exists and process is alive)
is_running() {
    if [ -f "$pid_file" ]; then
        local pid
        pid=$(cat "$pid_file")
        if kill -0 "$pid" 2>/dev/null; then
            return 0
        fi
    fi
    return 1
}

# Get number of connected clients from log (cheap check)
get_client_count() {
    if [ -f "$log_file" ]; then
        # Look for "New client" or "Closing" messages in the log
        # This is a heuristic; return 0 if can't determine
        grep -c "New client" "$log_file" 2>/dev/null || echo "0"
    else
        echo "0"
    fi
}

# Check if a port is accepting connections
port_ready() {
    # Use nc (netcat) or bash TCP redirection
    if command -v nc >/dev/null 2>&1; then
        nc -z localhost "$1" 2>/dev/null || return 1
    else
        # Bash TCP redirection fallback
        bash -c "exec 3<>/dev/tcp/localhost/$1" >/dev/null 2>&1 || return 1
    fi
    return 0
}

# Generate config file
generate_config() {
    cat > "$config_file" << CONF
# Test MQTT broker for OTA simulation (generated by mosquitto.sh)
listener $port 0.0.0.0
allow_anonymous true
persistence false
log_dest file $log_file
log_timestamp_format %Y-%m-%d %H:%M:%S
CONF
}

# Start the broker
action_up() {
    if is_running; then
        pid=$(cat "$pid_file")
        echo "[mosquitto] already running (pid $pid, listening on 0.0.0.0:$port)"
        
        # Detect and print LAN IP for convenience
        # shellcheck disable=SC1091
        if [ -f "$(dirname "$0")/lib.sh" ]; then
            # shellcheck source=/dev/null
            source "$(dirname "$0")/lib.sh"
            if lan_ip=$(detect_lan_ip 2>/dev/null); then
                echo "[mosquitto] Use: MQTT_HOST=$lan_ip MQTT_PORT=$port"
            fi
        fi
        return 0
    fi
    
    # Check if port is already in use by another process
    if port_ready "$port" 2>/dev/null; then
        echo "Error: port $port is already in use by another process" >&2
        exit 1
    fi
    
    generate_config
    
    # Start mosquitto in background
    "$mosquitto_bin" -c "$config_file" -d
    
    # Write pid to file (mosquitto -d doesn't write the pid)
    # Wait a moment for the process to start, then find its pid
    sleep 0.5
    local mosquitto_pid
    mosquitto_pid=$(pgrep -f "mosquitto.*-c.*$config_file" | head -1)
    if [ -n "$mosquitto_pid" ]; then
        echo "$mosquitto_pid" > "$pid_file"
    else
        echo "Error: failed to start mosquitto" >&2
        exit 1
    fi
    
    # Wait for port to be ready (up to 5 seconds)
    local attempts=0
    while [ $attempts -lt 10 ]; do
        if port_ready "$port" 2>/dev/null; then
            # Detect and print LAN IP
            # shellcheck disable=SC1091
            if [ -f "$(dirname "$0")/lib.sh" ]; then
                # shellcheck source=/dev/null
                source "$(dirname "$0")/lib.sh"
                if lan_ip=$(detect_lan_ip 2>/dev/null); then
                    echo "[mosquitto] listening on 0.0.0.0:$port"
                    echo "[mosquitto] Use: MQTT_HOST=$lan_ip MQTT_PORT=$port"
                    return 0
                fi
            fi
            echo "[mosquitto] listening on 0.0.0.0:$port"
            return 0
        fi
        sleep 0.5
        attempts=$((attempts + 1))
    done
    
    echo "Error: mosquitto did not become ready within 5 seconds" >&2
    exit 1
}

# Stop the broker
action_down() {
    if ! is_running; then
        echo "[mosquitto] not running"
        return 0
    fi
    
    pid=$(cat "$pid_file")
    echo "[mosquitto] stopping (pid $pid)"
    
    # Try graceful shutdown first
    if kill -TERM "$pid" 2>/dev/null; then
        # Wait for graceful shutdown (up to 3 seconds)
        local attempts=0
        while [ $attempts -lt 6 ]; do
            if ! kill -0 "$pid" 2>/dev/null; then
                rm -f "$pid_file"
                echo "[mosquitto] stopped"
                return 0
            fi
            sleep 0.5
            attempts=$((attempts + 1))
        done
        
        # Force kill if still running
        echo "[mosquitto] force killing"
        kill -9 "$pid" 2>/dev/null || true
        rm -f "$pid_file"
    else
        # Process not running; clean up pid file
        rm -f "$pid_file"
    fi
    
    echo "[mosquitto] stopped"
}

# Show status
action_status() {
    if is_running; then
        pid=$(cat "$pid_file")
        echo "[mosquitto] running (pid $pid, listening on 0.0.0.0:$port)"
        
        # Show last few log lines if available
        if [ -f "$log_file" ]; then
            echo ""
            echo "Recent log entries:"
            tail -3 "$log_file"
        fi
    else
        echo "[mosquitto] not running"
        
        # Show last few log lines from previous run if available
        if [ -f "$log_file" ]; then
            echo ""
            echo "Last entries from previous run:"
            tail -3 "$log_file"
        fi
    fi
}

# Main dispatch
case "$action" in
    up)
        action_up
        ;;
    down)
        action_down
        ;;
    status)
        action_status
        ;;
    restart)
        action_down
        action_up
        ;;
    *)
        echo "Error: unknown action '$action'" >&2
        usage
        ;;
esac
